updated dast with image name

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -24,249 +24,238 @@ permissions:
 
 jobs:
 
-#   clone:
-#     runs-on: ubuntu-latest
-#     steps:
-#     - name: checkout code
-#       uses: actions/checkout@v4
+  clone:
+    runs-on: ubuntu-latest
+    steps:
+    - name: checkout code
+      uses: actions/checkout@v4
 
-#     - name: Upload Source Code
-#       uses: actions/upload-artifact@v4
-#       with:
-#         name: source-code
-#         path: .
+    - name: Upload Source Code
+      uses: actions/upload-artifact@v4
+      with:
+        name: source-code
+        path: .
 
-#   build:
-#     needs: clone
-#     runs-on: ubuntu-latest
-#     container:
-#       image: maven:3.9-eclipse-temurin-17
-#       options: --user root
-#     steps:
+  # build:
+  #   needs: clone
+  #   runs-on: ubuntu-latest
+  #   container:
+  #     image: maven:3.9-eclipse-temurin-17
+  #     options: --user root
+  #   steps:
  
-#     - name: Download artifacts
-#       uses: actions/download-artifact@v4
-#       with:
-#         name: source-code
-#         path: .
+  #   - name: Download artifacts
+  #     uses: actions/download-artifact@v4
+  #     with:
+  #       name: source-code
+  #       path: .
 
-#     - name: Build the Source Code
-#       run: |
-#         mvn clean package -DskipTests
+  #   - name: Build the Source Code
+  #     run: |
+  #       mvn clean package -DskipTests
 
-#     - name: Upload Compile files target folder
-#       uses: actions/upload-artifact@v4
-#       with:
-#         name: compile-files
-#         path: target
+  #   - name: Upload Compile files target folder
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: compile-files
+  #       path: target
 
 
-#   bug-analysis:
-#     needs: build
-#     runs-on: ubuntu-latest
-#     container:
-#       image: maven:3.9-eclipse-temurin-17
-#       options: --user root
-#     steps:
-#     - name: Download artifacts
-#       uses: actions/download-artifact@v4
-#       with:
-#         name: source-code
-#         path: .
+  # bug-analysis:
+  #   needs: build
+  #   runs-on: ubuntu-latest
+  #   container:
+  #     image: maven:3.9-eclipse-temurin-17
+  #     options: --user root
+  #   steps:
+  #   - name: Download artifacts
+  #     uses: actions/download-artifact@v4
+  #     with:
+  #       name: source-code
+  #       path: .
 
-#     - name: Download artifacts
-#       uses: actions/download-artifact@v4
-#       with:
-#         name: compile-files
-#         path: target
+  #   - name: Download artifacts
+  #     uses: actions/download-artifact@v4
+  #     with:
+  #       name: compile-files
+  #       path: target
 
-#     - name: check files
-#       run: |
-#         ls -l
+  #   - name: check files
+  #     run: |
+  #       ls -l
 
-#     - name: Bug Analysis
-#       run: mvn com.github.spotbugs:spotbugs-maven-plugin:check
+  #   - name: Bug Analysis
+  #     run: mvn com.github.spotbugs:spotbugs-maven-plugin:check
   
 
-#     - name: Upload Bug report
-#       uses: actions/upload-artifact@v4
-#       with:
-#         name: bug-report
-#         path: target/*.xml
+  #   - name: Upload Bug report
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: bug-report
+  #       path: target/*.xml
 
-#   dependency-check:
-#     needs: clone
-#     runs-on: ubuntu-latest
-#     container:
-#       image: maven:3.9-eclipse-temurin-17
-#       options: --user root
-#     steps:
-#     - name: Download artifacts
-#       uses: actions/download-artifact@v4
-#       with:
-#         name: source-code
-#         path: .
-    
-#     - name: Check dependency check
-#       run: |
-#         mvn dependency-check:check
-
-#     - name: check file
-#       run: |
-#         ls -l
-
-#     - name: Upload Bug report
-#       uses: actions/upload-artifact@v4
-#       with:
-#         name: dependency-check-report
-#         path: dependency-check-report.html
-
-#   sca-sonar-alanysis:
-#     name: static code analysis
-#     needs: [build, bug-analysis, dependency-check]
-#     runs-on: ubuntu-latest
-#     container:
-#       image: maven:3.9-eclipse-temurin-17
-#       options: --user root
-#     steps:
-#     - name: Download artifacts
-#       uses: actions/download-artifact@v4
-#       with:
-#         name: source-code
-#         path: .
-
-
-#     - name: Download artifacts
-#       uses: actions/download-artifact@v4
-#       with:
-#         name: compile-files
-#         path: target
-
-#     - name: Download artifacts
-#       uses: actions/download-artifact@v4
-#       with:
-#         name: bug-report
-#         path: target
-
-
-#     - name: Download artifacts
-#       uses: actions/download-artifact@v4
-#       with:
-#         name: dependency-check-report
-#         path: target
-
-#     - name: Check files
-#       run: |
-#         ls -l
-#         ls -l target/
-
-#     - name: run sonar plugin
-#       run: |
-#        mvn sonar:sonar \
-#         -Dsonar.projectName=${{ github.event.repository.name }} \
-#         -Dsonar.projectKey=${{ github.event.repository.name }} \
-#         -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
-#         -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
-#         -Dsonar.coverage.jacoco.xmlReportPaths=jacoco.xml \
-#         -Dsonar.dependencyCheck.htmlReportPath=dependency-check-report.html  \
-#         -Dsonar.findbugs.reportpaths=target/spotbugsXml.xml \
-#         -Dsonar.qualitygate.wait=true
-
-
-
-#   docker-build-push:
-#     runs-on: ubuntu-latest
-#     env: 
-#       ECR_REPO: 'salary-api'
-#       AWS_REGION: 'ap-south-1'
-#     needs: sca-sonar-alanysis
-#     outputs:
-#       image_tag: ${{ steps.vars.outputs.image_tag }}
-#       image-name: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}
-#     steps:
-#       - name: Download source code
-#         uses: actions/download-artifact@v4
-#         with:
-#           name: source-code
-#           path: .
-
-#       - name: Remove target folder after download
-#         run: rm -rf ./target
-
-#       - name: Configure AWS credentials
-#         uses: aws-actions/configure-aws-credentials@v4
-#         with:
-#           role-to-assume: ${{ secrets.AWS_IAM_ROLE_ATHENTICATION }}
-#           role-session-name: GitHubActionSession
-#           aws-region: ${{ env.AWS_REGION }}
-
-#       - name: Log in to Amazon ECR
-#         id: login-ecr
-#         uses: aws-actions/amazon-ecr-login@v1
-
-
-#       - name: Set Image Tags
-#         id: vars
-#         run: |
-#           IMAGE_TAG=${{ github.ref_name }}-$(echo $GITHUB_SHA | head -c 8)
-#           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
-#           echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
-
-
-#       - name: Build and Push Docker Image
-#         uses: docker/build-push-action@v5
-#         with:
-#           context: .
-#           push: true
-#           tags: |
-#             ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
-
-#       - name: Upload ecr image scan file
-#         uses: actions/upload-artifact@v4
-#         with:
-#           name: ecr-scan-file
-#           path: ecr-image-scan.sh
-
-#   docker-image-scan:
-#     runs-on: ubuntu-latest
-#     env: 
-#       ECR_REPO: 'salary-api'
-#       AWS_REGION: 'ap-south-1'
-#     needs: docker-build-push
-#     steps:
-#       - name: Download ecr image scan file
-#         uses: actions/download-artifact@v4
-#         with:
-#           name: ecr-scan-file
-#           path: .
-
-#       - name: Configure AWS credentials
-#         uses: aws-actions/configure-aws-credentials@v4
-#         with:
-#           role-to-assume: ${{ secrets.AWS_IAM_ROLE_ATHENTICATION }}
-#           role-session-name: GitHubActionSession
-#           aws-region: ${{ env.AWS_REGION }}
-
-#       - name: Install JQ
-#         run: sudo apt-get update && sudo apt-get install -y jq
-
-#       - name: Run ECR Vulnerability Scan Check
-#         run: |
-#           chmod +x ./ecr-image-scan.sh && ./ecr-image-scan.sh ${{ env.ECR_REPO }} ${{ needs.docker-build-push.outputs.image_tag }} ${{ env.AWS_REGION }}
-
-
-  # test:
+  # dependency-check:
+  #   needs: clone
   #   runs-on: ubuntu-latest
+  #   container:
+  #     image: maven:3.9-eclipse-temurin-17
+  #     options: --user root
   #   steps:
-  #   - name: checkout
-  #     uses:  actions/checkout@v4
-
-  #   - name: test
+  #   - name: Download artifacts
+  #     uses: actions/download-artifact@v4
+  #     with:
+  #       name: source-code
+  #       path: .
+    
+  #   - name: Check dependency check
   #     run: |
-  #       ls -l $(pwd)
+  #       mvn dependency-check:check
+
+  #   - name: check file
+  #     run: |
+  #       ls -l
+
+  #   - name: Upload Bug report
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: dependency-check-report
+  #       path: dependency-check-report.html
+
+  # sca-sonar-alanysis:
+  #   name: static code analysis
+  #   needs: [build, bug-analysis, dependency-check]
+  #   runs-on: ubuntu-latest
+  #   container:
+  #     image: maven:3.9-eclipse-temurin-17
+  #     options: --user root
+  #   steps:
+  #   - name: Download artifacts
+  #     uses: actions/download-artifact@v4
+  #     with:
+  #       name: source-code
+  #       path: .
+
+
+  #   - name: Download artifacts
+  #     uses: actions/download-artifact@v4
+  #     with:
+  #       name: compile-files
+  #       path: target
+
+  #   - name: Download artifacts
+  #     uses: actions/download-artifact@v4
+  #     with:
+  #       name: bug-report
+  #       path: target
+
+
+  #   - name: Download artifacts
+  #     uses: actions/download-artifact@v4
+  #     with:
+  #       name: dependency-check-report
+  #       path: .
+
+  #   - name: run sonar plugin
+  #     run: |
+  #      mvn sonar:sonar \
+  #       -Dsonar.projectName=${{ github.event.repository.name }} \
+  #       -Dsonar.projectKey=${{ github.event.repository.name }} \
+  #       -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
+  #       -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
+  #       -Dsonar.coverage.jacoco.xmlReportPaths=jacoco.xml \
+  #       -Dsonar.dependencyCheck.htmlReportPath=dependency-check-report.html  \
+  #       -Dsonar.findbugs.reportpaths=target/spotbugsXml.xml \
+  #       -Dsonar.qualitygate.wait=true
+
+
+
+  docker-build-push:
+    runs-on: ubuntu-latest
+    env: 
+      ECR_REPO: 'salary-api'
+      AWS_REGION: 'ap-south-1'
+    # needs: sca-sonar-alanysis
+    outputs:
+      image_tag: ${{ steps.vars.outputs.image_tag }}
+      image-name: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}
+    steps:
+      - name: Download source code
+        uses: actions/download-artifact@v4
+        with:
+          name: source-code
+          path: .
+
+      # - name: Remove target folder after download
+      #   run: rm -rf ./target
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ATHENTICATION }}
+          role-session-name: GitHubActionSession
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Log in to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v1
+
+
+      - name: Set Image Tags
+        id: vars
+        run: |
+          IMAGE_TAG=${{ github.ref_name }}-$(echo $GITHUB_SHA | head -c 8)
+          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
+          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
+
+
+      - name: Build and Push Docker Image
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          push: true
+          tags: |
+            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
+
+      - name: Upload ecr image scan file
+        uses: actions/upload-artifact@v4
+        with:
+          name: ecr-scan-file
+          path: ecr-image-scan.sh
+
+  docker-image-scan:
+    runs-on: ubuntu-latest
+    env: 
+      ECR_REPO: 'salary-api'
+      AWS_REGION: 'ap-south-1'
+    needs: docker-build-push
+    steps:
+      - name: Download ecr image scan file
+        uses: actions/download-artifact@v4
+        with:
+          name: ecr-scan-file
+          path: .
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ATHENTICATION }}
+          role-session-name: GitHubActionSession
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Install JQ
+        run: sudo apt-get update && sudo apt-get install -y jq
+
+      - name: Run ECR Vulnerability Scan Check
+        run: |
+          chmod +x ./ecr-image-scan.sh && ./ecr-image-scan.sh ${{ env.ECR_REPO }} ${{ needs.docker-build-push.outputs.image_tag }} ${{ env.AWS_REGION }}
+
 
   dast:
+    needs: [docker-image-scan, docker-build-push]
     runs-on: ubuntu-latest
+    env:
+     env:
+      IMAGE_NAME: ${{ needs.docker-build-push.outputs.image-name }}:${{ needs.docker-build-push.outputs.image_tag }}
     steps:
       - name: checkout
         uses: actions/checkout@v4
@@ -276,7 +265,8 @@ jobs:
 
       - name: Start application
         run: |
-          docker compose -f docker-compose.yaml up -d
+          echo "IMAGE_NAME=${{ needs.docker-build-push.outputs.image-name }}:${{ needs.docker-build-push.outputs.image_tag }}" > .env
+          docker compose up -d
 
 
       - name: Run ZAP scan
@@ -284,7 +274,7 @@ jobs:
           sleep 30
           set +e  # disable "exit on error" for this block
           docker run --network host -u root -v $(pwd):/zap/wrk ghcr.io/zaproxy/zaproxy:stable \
-            zap-full-scan.py -t http://localhost:8080 -r report.html -z "-config urls.file=/zap/wrk/urls.txt"
+            zap-full-scan.py -t http://localhost:8080 -J report.json -z "-config urls.file=/zap/wrk/urls.txt"
           
           exit_code=$?
           echo "ZAP exited with code: $exit_code"
@@ -296,18 +286,21 @@ jobs:
 
           exit $exit_code  # Let GitHub Action fail only for real errors (1 or 3)
 
+      - name: Validate ZAP Report for High Risk Issues
+        run: |
+          if grep -q 'High' report.json; then
+            echo "High risk issues found in report!"
+            exit 1  # Fail the job if 'High' found
+          else
+            echo "No High risk issues found in report."
+          fi
 
 
-
-      - name: check report files
-        run: | 
-          ls -l
-
-      - name: Upload ZAP Report
-        uses: actions/upload-artifact@v4
-        with:
-          name: zap-report
-          path: report.html
+      # - name: Upload ZAP Report
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: zap-report
+      #     path: report.html
 
 
 #   # trigger-CD:
