checking commit signoff

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -5,41 +5,58 @@ on:
     branches: ['main']
 
 
-# # on:
-# #   push:
-# #     branches:
-# #       - dev
-# #       - 'feature/*'
-# #       - 'release/*'
-# #       - main
-# #   pull_request:
-# #     branches:
-# #       - main
+# on:
+#   push:
+#     branches:
+#       - dev
+#       - 'feature/*'
+#       - 'release/*'
+#       - main
+#   pull_request:
+#     branches:
+#       - main
 
 
-# permissions:
-#   id-token: write
-#   contents: read  
-#   packages: write
+permissions:
+  id-token: write
+  contents: read  
+  packages: write
 
-# jobs:
+jobs:
 
-#   credential-scan:
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Checkout repository
-#         uses: actions/checkout@v3 
+  credential_scan-commit_sign-off:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v3 
 
-#       - uses: gitleaks/gitleaks-action@v2
-#         with:
-#           args: --verbose --redact --exit-code 1
+    - uses: gitleaks/gitleaks-action@v2
+      with:
+        args: --verbose --redact --exit-code 1
 
-#       - name: Upload Source Code
-#         uses: actions/upload-artifact@v4
-#         with:
-#           name: source-code
-#           path: .
+    - name: check for commit sign-off
+      run: |
+        git log -1 --pretty=%B | grep -q "Signed-off-by:"
 
+        if [[ $? -eq 0]]; then
+          echo "commit is missing Signed-off-by line"
+          exit 1
+        fi
+        
+    - name: check for commit sign-off
+      run: |
+        git log -1 --pretty=%B | grep -q "Signed-off-by:"
+
+        if [[ $? -eq 0]]; then
+          echo "commit is missing Signed-off-by line"
+          exit 1
+        fi
+
+    - name: Upload Source Code
+      uses: actions/upload-artifact@v4
+      with:
+        name: source-code
+        path: .
   # build:
   #   needs: clone
   #   runs-on: ubuntu-latest
