Checking dast

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -281,12 +281,20 @@ jobs:
 
       - name: Run ZAP scan
         run: |
+          # Sleep for 30 seconds to ensure the app is fully up and running
           sleep 30
 
-
+          # Run ZAP scan and suppress error output
           docker run --network host -u root -v $(pwd):/zap/wrk ghcr.io/zaproxy/zaproxy:stable \
             zap-full-scan.py -t http://localhost:8080 -r report.html \
-            -z "-config urls.file=/zap/wrk/urls.txt" 2> /dev/null; (($? == 2)) && echo 'Done' >&2
+            -z "-config urls.file=/zap/wrk/urls.txt" 2> /dev/null
+
+          # Check if the exit code was 2 (warning level)
+          if (($? == 2)); then
+            echo 'Done' >&2
+          fi
+
+
       - name: check report files
         run: | 
           ls -l
